Web/Controllers/ClientController.cs
using System.Linq;
using System.Web.Mvc;
using Nocturne.Common.Interfaces;
using Nocturne.Common.Models;
using Web.Models;

namespace Nocturne.Web.Controllers
{
    [Authorize]
    public class ClientController : BaseController
    {
        private readonly IUOW _uow;

        public ClientController(IUOW uow)
        {
            _uow = uow;
        }

        // GET: Client
        public ActionResult Index()
        {
            var clients = _uow.Clients.GetAllClients().OrderBy(c => c.IdCode).ToArray();
            return View(new ClientIndexViewModel() { Clients = clients});
        }

        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            var client = _uow.Clients.GetClient(id);
            return View(new ClientCreateEditDetailsViewModel() { Client = client});
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            var client = new Client();
            return View(new ClientCreateEditDetailsViewModel() { Client = client});
        }

        // POST: Client/Create
        [HttpPost]
        public ActionResult Create(ClientCreateEditDetailsViewModel vm)
        {
            try
            {
                var validationResult = _uow.Clients.SaveClient(vm.Client);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            return View(vm);
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            var client = _uow.Clients.GetClient(id);
            return View(new ClientCreateEditDetailsViewModel() {Client = client});
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(ClientCreateEditDetailsViewModel vm)
        {
            try
            {
                var validationResult = _uow.Clients.SaveClient(vm.Client);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            return View(vm);
        }
    }
}

Web/Controllers/DiscountController.cs
using Nocturne.Common.Interfaces;
using Nocturne.Common.Models;
using System.Linq;
using System.Web.Mvc;
using Web.Models;

namespace Nocturne.Web.Controllers
{
    [Authorize]
    public class DiscountController : BaseController
    {
        private readonly IUOW _uow;

        public DiscountController(IUOW uow)
        {
            _uow = uow;
        }


        // GET: Discount
        public ActionResult Index()
        {
            var discounts = _uow.Discounts.GetAllDiscounts().ToList();
            var discountTypes = _uow.DiscountTypes.GetAllDiscountTypes();
            var products = _uow.Products.GetAllProducts();
            discounts.ForEach(d => d.DiscountType = discountTypes.Single(dt => dt.Id == d.DiscountTypeId));
            discounts.ForEach(d => d.Product = products.Single(p => p.Id == d.ProductId));
            return View(new DiscountIndexViewModel() { Discounts = discounts.OrderBy(c => c.Id).ToArray() });
        }

        // GET: Discount/Details/5
        public ActionResult Details(int id)
        {
            var discount = _uow.Discounts.GetDiscount(id);
            var discountTypes = _uow.DiscountTypes.GetAllDiscountTypes();
            var products = _uow.Products.GetAllProducts();
            discount.DiscountType = discountTypes.Single(dt => dt.Id == discount.DiscountTypeId);
            discount.Product = products.Single(p => p.Id == discount.ProductId);
            return View(new DiscountDetailsViewModel() { Discount = discount });
        }

        // GET: Discount/Create
        public ActionResult Create()
        {
            var discount = new Discount();
            var vm = new DiscountCreateEditViewModel() { Discount = discount };
            FillDropdowns(vm);
            return View(vm);
        }

        // POST: Discount/Create
        [HttpPost]
        public ActionResult Create(DiscountCreateEditViewModel vm)
        {
            try
            {
                var validationResult = _uow.Discounts.SaveDiscount(vm.Discount);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }

                    FillDropdowns(vm);

                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            FillDropdowns(vm);
            return View(vm);
        }

        // GET: Discount/Edit/5
        public ActionResult Edit(int id)
        {
            var discount = _uow.Discounts.GetDiscount(id);
            var vm = new DiscountCreateEditViewModel() { Discount = discount };
            FillDropdowns(vm);
            return View(vm);
        }

        // POST: Discount/Edit/5
        [HttpPost]
        public ActionResult Edit(DiscountCreateEditViewModel vm)
        {
            try
            {
                var validationResult = _uow.Discounts.SaveDiscount(vm.Discount);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }

                    FillDropdowns(vm);
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            FillDropdowns(vm);
            return View(vm);
        }

        private void FillDropdowns(DiscountCreateEditViewModel vm)
        {
            var discountTypes = _uow.DiscountTypes.GetAllDiscountTypes();
            vm.DiscountTypeSelector = new SelectList(discountTypes, "Id", "Name.Value");
            var products = _uow.Products.GetAllProducts();
            vm.ProductsSelector = new SelectList(products, "Id", "Name.Value");
        }
    }
}

Web/Controllers/ProductController.cs
using Nocturne.Common.Models;
using System.Linq;
using System.Web.Mvc;
using Nocturne.Common.Interfaces;
using Web.Models;

namespace Nocturne.Web.Controllers
{
    [Authorize]
    public class ProductController : BaseController
    {
        private readonly IUOW _uow;

        public ProductController(IUOW uow)
        {
            _uow = uow;
        }

        // GET: Product
        public ActionResult Index()
        {
            var products = _uow.Products.GetAllProducts().OrderBy(c => c.Name.Value).ToList();

            products.ForEach(p => p.Name.Translations =
                _uow.Translations.GetTranslationsByMultiLangStringId(p.Name.MultiLangStringId).ToList());

            products.ForEach(p => p.Description.Translations =
                _uow.Translations.GetTranslationsByMultiLangStringId(p.Description.MultiLangStringId).ToList());

            return View(new ProductIndexViewModel() {Products = products.ToArray() });
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            var product = _uow.Products.GetProduct(id);
            return View(new ProductCreateEditDetailsViewModel() { Product = product });
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            var product = new Product();
            return View(new ProductCreateEditDetailsViewModel() { Product = product });
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(ProductCreateEditDetailsViewModel vm)
        {
            try
            {
                var validationResult = _uow.Products.SaveProduct(vm.Product);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            return View(vm);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _uow.Products.GetProduct(id);
            return View(new ProductCreateEditDetailsViewModel() {Product = product });
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(ProductCreateEditDetailsViewModel vm)
        {
            try
            {
                var validationResult = _uow.Products.SaveProduct(vm.Product);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            return View(vm);
        }

    }
}

Web/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using Nocturne.Common.Interfaces;
using Nocturne.Common.Models;
using Web.Models;

namespace Nocturne.Web.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private readonly IUOW _uow;

        public UserController(IUOW uow)
        {
            _uow = uow;
        }


        // GET: User
        public ActionResult Index()
        {
            var users = _uow.Users.GetAllUsers().OrderBy(c => c.Name).ToArray();
            return View(new UserIndexViewModel() { Users = users});
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            var user = _uow.Users.GetUser(id);
            return View(new UserCreateEditDetailsViewModel() {User = user});
        }

        // GET: User/Create
        public ActionResult Create()
        {
            var user = new User();
            return View(new UserCreateEditDetailsViewModel() { User = user });
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(UserCreateEditDetailsViewModel vm)
        {
            try
            {
                var validationResult = _uow.Users.SaveUser(vm.User);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            return View(vm);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {

            var user = _uow.Users.GetUser(id);
            return View(new UserCreateEditDetailsViewModel() { User = user });
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(UserCreateEditDetailsViewModel vm)
        {
            try
            {
                var validationResult = _uow.Users.SaveUser(vm.User);
                if (validationResult.HasValidationMessageType<ValidationErrorMessage>())
                {
                    foreach (var validationMessage in validationResult.Messages)
                    {
                        foreach (var message in validationMessage.Value)
                        {
                            ModelState.AddModelError(validationMessage.Key, message.Message);
                        }
                    }
                    return View(vm);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "System error. Try again later.");
            }
            return View(vm);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
@model Web.Models.ViewModelBase

@{
    var nameValueCollection = HttpUtility.ParseQueryString(Request?.Url?.Query ?? "");
    nameValueCollection.Remove("culture");
    string returnUrl = Request?.Url?.AbsolutePath + "?" + nameValueCollection;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Model.Title | Nocturne</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700,400italic'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <!-- Aside navigation bar (static) -->
    <aside class="Aside__block">
        <a href="/" class="here" title="Home"><i class="fa fa-home fa-lg" aria-hidden="true"></i></a>
        <a href="/Client" title="Clients"><i class="fa fa-thumbs-o-up fa-lg" aria-hidden="true"></i></a>
        <a href="/User" title="Users"><i class="fa fa-users fa-lg" aria-hidden="true"></i></a>
        <a href="/Product" title="Products"><i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i></a>
        <a href="/Discount" title="Discounts"><i class="fa fa-tag fa-lg" aria-hidden="true"></i></a>
        <a href="/DiscountType" title="Discount types"><i class="fa fa-tags fa-lg" aria-hidden="true"></i></a>
        <a href="/Account/Logoff" title="Sign In"><i class="fa fa-sign-in" aria-hidden="true"></i></a>
    </aside>

    <div class="Header container-fluid">
        <img class="Header__logo" src="/Content/images/logo.png" alt="Logotype" />
        <div class="Header_right">
            <span class="Header__clients"><strong id="clients">@Model.ClientCount</strong> clients</span>
            <span class="Header__time" id="time"></span>
        </div>
        <div>

            @Html.ActionLink("Est", "SetLanguage", new { area = "", controller = "Language", culture = "et", returnUrl }, htmlAttributes: new { id = "langLinkEst" })
            @Html.ActionLink("Eng", "SetLanguage", new { area = "", controller = "Language", culture = "en", returnUrl }, htmlAttributes: new { id = "langLinkEng" })


        </div>
    </div>

    <div class="navbar navbar-inverse navbar-fixed-top" style="display:none">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Symphony POSS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clients", "Index", "Client")</li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Discounts", "Index", "Discount")</li>
                    <li>@Html.ActionLink("Discount Types", "Index", "DiscountType")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content Content">
        <h1 class="Content__title">@Model.Title</h1>
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - Symphony No. 7 in C-sharp minor</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        // Timer
        function checkTime(i) {
          if (i < 10) {
              i = "0" + i;
          }
          return i;
        }
        function startTime() {
            var today = new Date();
            var h = today.getHours();
            var m = today.getMinutes();
            var s = today.getSeconds();
            // add a zero in front of numbers<10
            m = checkTime(m);
            s = checkTime(s);
            document.getElementById('time').innerHTML = h + ":" + m;
            t = setTimeout(function () {
                startTime()
            }, 500);
        }
        startTime();
    </script>
</body>
</html>